server:
  port: 8080


logging:
  level:
    root: info


langchain4j:
  open-ai:
    chat-model:
      api-key: demo
      model-name: gpt-4o-mini
      log-requests: true # 请求日志
      log-responses: true # 响应日志
      base-url: http://langchain4j.dev/demo/openai/v1