server:
  port: 8080


logging:
  level:
    root: info



# 阿里百炼
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-max
      # 向量模型
      embedding-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: text-embedding-v3

# Open-ai
#langchain4j:
#  open-ai:
#    chat-model:
#       api-key: demo
#       model-name: gpt-4o-mini
#       log-requests: true # 请求日志
#       log-responses: true # 响应日志
#       base-url: http://langchain4j.dev/demo/openai/v1

# DeepSeek
#langchain4j:
#  open-ai:
#    chat-model:
#      api-key: ${DEEP_SEEK_API_KEY}
#      model-name: deepseek-chat
#      log-requests: true # 请求日志
#      log-responses: true # 响应日志
#      base-url: https://api.deepseek.com

# ollama本地部署的模型
#langchain4j:
#  ollama:
#    base-url: http://localhost:11434


